services:
  neo4j-db:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/data:/data
    networks:
      - desire

  friends-service:
    build: ./
    image: friends-service
    container_name: friends-service
    environment:
      SPRING_APPLICATION_NAME: friends-service
      SPRING_DATA_NEO4J_URI: bolt://neo4j-db:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka
    ports:
      - "5003:8080"
    depends_on:
      - neo4j-db
    networks:
      - desire

networks:
  desire:
    external: true